[package]
name = "esp_hal_probe"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"

[dependencies]
defmt = "0.3"
defmt-rtt = "0.4"
embassy-executor = { version = "0.6", features = ["defmt"] }
embassy-time = { version = "0.3", features = ["generic-queue-8"] }
esp-backtrace = { version = "0.14", features = [
  "esp32c3",
  "defmt",
  "exception-handler",
  "panic-handler",
] }
esp-hal = { version = "0.20", features = ["esp32c3", "defmt"] }
esp-hal-embassy = { version = "0.3", features = ["esp32c3", "defmt"] }

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
opt-level = 3
lto = 'fat'
overflow-checks = false

[patch.crates-io]
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "f2e0211c1b7b0c181374c0e85ac209fa3ddca796" }
esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", rev = "f2e0211c1b7b0c181374c0e85ac209fa3ddca796" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", rev = "f2e0211c1b7b0c181374c0e85ac209fa3ddca796" }

