[package]
name         = "esp_hal_probe"
version      = "0.1.0"
edition      = "2021"
rust-version = "1.76.0"

[dependencies]
bt-hci           = "0.1.0"
defmt            = "0.3"
defmt-rtt        = "0.4"
embassy-executor = { version = "0.6",  features = ["defmt"] }
embassy-time     = { version = "0.3",  features = ["generic-queue-8"] }
esp-alloc        = "0.4.0"
esp-backtrace    = { version = "0.14", features = ["esp32c3", "defmt", "exception-handler", "panic-handler"] }
esp-hal          = { version = "0.20", features = ["esp32c3", "defmt"] }
esp-hal-embassy  = { version = "0.3",  features = ["esp32c3", "defmt"] }
esp-wifi         = { version = "0.9",  default-features = false, features = ["defmt", "esp32c3", "ble", "async", "esp-alloc"] }
trouble-host     = { default-features = false, features = ["defmt", "gatt" ], git = "https://github.com/embassy-rs/trouble", package = "trouble-host", rev = "d9d2e80b6b2ed6c3aeae1de534de557906353522"}

[profile.release]
codegen-units    = 1
debug            = 2
debug-assertions = false
incremental      = false
opt-level        = 3
lto = 'fat'
overflow-checks  = false

[patch.crates-io]
esp-hal = { git = "https://github.com/esp-rs/esp-hal", rev = "312746fb14f3273430b52ae6dfff3943b39ee51f" }
esp-hal-embassy = { git = "https://github.com/esp-rs/esp-hal", rev = "312746fb14f3273430b52ae6dfff3943b39ee51f" }
esp-backtrace = { git = "https://github.com/esp-rs/esp-hal", rev = "312746fb14f3273430b52ae6dfff3943b39ee51f" }
esp-wifi = { git = "https://github.com/esp-rs/esp-hal", rev = "312746fb14f3273430b52ae6dfff3943b39ee51f" }
esp-alloc = { git = "https://github.com/esp-rs/esp-hal", rev = "312746fb14f3273430b52ae6dfff3943b39ee51f" }