[package]
name         = "esp_hal_probe"
version      = "0.1.0"
edition      = "2021"
rust-version = "1.76.0"

[dependencies]
defmt            = "0.3"
defmt-rtt        = "0.4"
embassy-executor = { version = "0.6",  features = ["defmt"] }
embassy-time     = { version = "0.3",  features = ["generic-queue-8"] }
embassy-futures = "0.1"
esp-backtrace    = { version = "0.14", features = ["esp32c3", "defmt", "exception-handler", "panic-handler"] }
esp-hal          = { version = "0.20", features = ["esp32c3", "defmt", "async"] }
esp-hal-embassy  = { version = "0.3",  features = ["esp32c3", "defmt"] }
static_cell      = { version = "2.1",  features = ["nightly"] }

[profile.release]
debug         = true  # Debug info is useful, and does not affect the size of the final binary
codegen-units = 1     # LLVM can perform better optimizations using a single thread
lto           = "fat" # Attempt to perform optimizations across all crates within the dependency graph
opt-level     = "s"   # Optimize for binary size, but keep loop vectorization enabled
